[metadata]
name = RoundPipe
version = 0.1.2
author = ITcarrot
author_email = luo-yb25@mails.tsinghua.edu.cn
description = Large DNNs training framework for consumer GPUs
long_description = file: README.md
long_description_content_type = text/markdown
url = https://thustorage.github.io/RoundPipe
license = Apache-2.0
license_files =
    LICENSE
    NOTICE.txt
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    beartype
    ninja
    py-cpuinfo
    torch>=2.4
    tqdm
    typing-extensions>=4.6.0

[options.extras_require]
docs =
    mkdocs
    mkdocs-material
    mkdocstrings[python]
    mkdocs-static-i18n[material]
    matplotlib

dev =
    pre-commit
    pytest
    pytest-xdist
    nvtx

[options.package_data]
roundpipe = 
    optim/csrc/*.cpp

[options.packages.find]
exclude =
    tests*
